### PR TITLE
Make sure no zero-bitsize connections appear

### PR DESCRIPTION
**Pull request by mpharrigan**
This adds additional assertions to `qualtran.testing` to make sure none of the `Connection` objects have zero bitsize. The presence of such registers/connections likely breaks assumptions used by the rest of the library. cc #1102 

Originally, I was going to add asserts to the `QDType`s themselves, but 1) they're used in several places other than defining registers that actually appear in a composite bloq causing "false positives" in the test 2) performing those assertions at QDType instantiation makes it impossible to get around; whereas this current change will only result in a failure if you're using `qlt_testing.assert_valid_bloq_decomposition` or its friends (or the `bloq_autotester`) so this PR probably has some false negatives still remaining.

### CODE REVIEW

**Comment by mpharrigan** [comment]
cc @NoureldinYosri found this in reviewing #1057

**Comment by mpharrigan** [comment]
@tanujkhattar `test_select_swap_qrom` results in zero-sized registers for the 3rd data example of `[[1],[2],[3]]`. Can you fix? 

https://github.com/quantumlib/Qualtran/blob/e2c6b82f0315ccfbdd1ebe9f65c8f1b324fc0c05/qualtran/bloqs/data_loading/qrom_base.py#L227

**Comment by mpharrigan** [comment]
`StatePreparationViaRotations`

https://github.com/quantumlib/Qualtran/blob/cf2044d9eecae76c8165d2405ee858d32986b647/qualtran/bloqs/state_preparation/state_preparation_via_rotation.py#L160

passed as selection bitsize to `PRGAViaPhaseGradient`. I don't know if this should actually be zero and the selection register needs to be omitted or if we still use a selection bit to select 1 value

@tanujkhattar can you fix

**Comment by mpharrigan** [comment]
@tanujkhattar can you approve. Looks like the failures are indeed fixed :)

**Review by tanujkhattar — APPROVED** [review]

**Pull request merged**
