### PR TITLE
Update Bartiq demo to work with version 0.6.0

### PR DESCRIPTION
**Pull request by mstechly**
This PR contains changes necessary for Baritq demo to work with Bartiq 0.6.0, which we plan to release soon.

### CODE REVIEW

**Comment by mstechly** [comment]
@mpharrigan – could you please make another PR to fix `qref==0.7.0` and `bartiq==0.6.0` to avoid issues with future releases?

**Comment by mpharrigan** [comment]
Since I can't bump the dependencies without simultaneously fixing the notebook, I pushed the dependency bump into this PR. PTAL

**Comment by mpharrigan** [comment]
looks like a real test failure in the bartiq notebook

**Comment by mstechly** [comment]
Yes, sorry for that.
It should be fixed now!

**Review by mpharrigan — APPROVED** [review]

**Comment by mstechly** [comment]
Thanks @mpharrigan 🎉

**Pull request merged**
