### PR TITLE
Don't run pylint on deleted files.

### PR DESCRIPTION
**Pull request by fdmalone**
I noticed in #1008 that ./check/pylint-changed-files would choke because I deleted some files. This PR adds a flag to filter out deleted files.

### CODE REVIEW

**Review by pavoljuhas — APPROVED** [review]
LGTM.  Please also fix missing quotes reported by shellcheck
```
$ shellcheck -f gcc check/pylint-changed-files 
check/pylint-changed-files:49:24: note: Double quote to prevent globbing and word splitting. [SC2086]
check/pylint-changed-files:50:23: note: Double quote to prevent globbing and word splitting. [SC2086]
```

**Comment by mpharrigan** [comment]
@pavoljuhas is this bug fixed in the cirq version of this script? can we make sure the two scripts don't diverge too much

**Comment by fdmalone** [comment]
> LGTM. Please also fix missing quotes reported by shellcheck
> 
> ```
> $ shellcheck -f gcc check/pylint-changed-files 
> check/pylint-changed-files:49:24: note: Double quote to prevent globbing and word splitting. [SC2086]
> check/pylint-changed-files:50:23: note: Double quote to prevent globbing and word splitting. [SC2086]
> ```

Done. Also just learned shellcheck existed!

**Comment by pavoljuhas** [comment]
> @pavoljuhas is this bug fixed in the cirq version of this script? can we make sure the two scripts don't diverge too much

Not yet.  This can wait after the cirq release.  (https://github.com/quantumlib/Cirq/issues/6619)

**Pull request merged**
