### PR TITLE
Skip slow tests in `pytest` CI workflow

### PR DESCRIPTION
**Pull request by charlesyuan314**
The goal of this change is to increase the speed of the per-PR `pytest` CI workflow.

We are now running all tests (including `slow` and `notebook`) nightly in a separate workflow.

### CODE REVIEW

**Comment by charlesyuan314** [comment]
With 4 workers, this change speeds up pytest for me locally from 32.3 mins to 12.5 mins. The speedup would increase further with #1228 and #1227.

**Comment by mpharrigan** [comment]
do you have numbers for the github actions CI speedup?

note: the notebooks are all run as part of a PR as well, just in their own job

**Comment by charlesyuan314** [comment]
I'll provide those numbers once #1228 is also merged.

For my own knowledge, should we be adding more `@pytest.mark.notebook` tests from now on, or relying on the` notebook` workflow?

**Comment by charlesyuan314** [comment]
On GitHub CI, we go from [19m 2s](https://github.com/quantumlib/Qualtran/actions/runs/10188052961/job/28183396308) to [4m 41s](https://github.com/quantumlib/Qualtran/actions/runs/10188247491/job/28184020405?pr=1229)!

**Review by mpharrigan — APPROVED** [review]
lovely

**Pull request merged**
