### PR TITLE
Add `BitwiseNot`

### PR DESCRIPTION
**Pull request by anurudhp**

### CODE REVIEW

**Review by charlesyuan314 — APPROVED** [review]

**Comment by NoureldinYosri** [comment]
why do we need this when we have [XorK](https://github.com/quantumlib/Qualtran/blob/22b3d5e2062610e908484e46d04771cc25aba56c/qualtran/bloqs/arithmetic/bitwise.py#L46)?

**Comment by anurudhp** [comment]
> why do we need this when we have [XorK](https://github.com/quantumlib/Qualtran/blob/22b3d5e2062610e908484e46d04771cc25aba56c/qualtran/bloqs/arithmetic/bitwise.py#L46)?

Just a convenient bloq to use instead of the less readable `XorK(dtype, -1)` or `XorK(dtype, 2**bitsize-1)`. And also avoids the detour of computing `bits(k)` etc.

**Comment by NoureldinYosri** [comment]
> Just a convenient bloq to use instead of the less readable


```py3
class XorK:
    ...

    @staticmethod
    def bitwise_not(dtype):
        return ...
```

**Comment by tanujkhattar** [comment]
I support having an additional Bloq instead of delagating to `XorK`. It would also be more readable in diagrams. Classical programming languages also have both `Xor` and `-` operators defined, even though one could always write `a ^ 2**size - 1` instead of `~a`.

**Pull request merged**
