### PR TITLE
Implement classical action of Cast bloq

### PR DESCRIPTION
**Pull request by NoureldinYosri**
fixes https://github.com/quantumlib/Qualtran/issues/734

blocking https://github.com/quantumlib/Qualtran/pull/1057

### CODE REVIEW

**Review by fdmalone — APPROVED** [review]
Add a test?

**Comment by fdmalone** [comment]
Oh, unhashable Fxp issues

**Comment by mpharrigan** [comment]
why is it trying to cache a fxp?

**Comment by NoureldinYosri** [comment]
I created https://github.com/quantumlib/Qualtran/issues/1095 to track support for QFxp

**Pull request merged**
