### PR TITLE
Add openfermion to pytest env.

### PR DESCRIPTION
**Pull request by fdmalone**
Add openfermion to the pytest environment #395 and needed for #409

### CODE REVIEW

**Comment by fdmalone** [comment]
I noticed this warning when re pip compiling in the docker container:

```
# The following packages are considered to be unsafe in a requirements file:
# pip
# setuptools
```

**Comment by fdmalone** [comment]
Actually hold off on this for the moment. @mpharrigan What's the best way to pull in the additional requirements required for resource estimates. I also need to cut an openfermion release for pbc resources.

**Comment by mpharrigan** [comment]
> I noticed this warning when re pip compiling in the docker container:

this isn't a warning so much as a note it puts in

**Comment by mpharrigan** [comment]
> What's the best way to pull in the additional requirements required for resource estimates. I also need to cut an openfermion release for pbc resources.

I'd say this current approach is correct. Mark the PR as draft if it's not ready to merge

**Review by mpharrigan — APPROVED** [review]

**Pull request merged**
