### PR TITLE
Don't silently omit counts from missing callees

### PR DESCRIPTION
**Pull request by mpharrigan**
Addresses the buggy part of #1290 by re-raising the error. Better error messages from Controlled(Atomic).

### CODE REVIEW

**Review by anurudhp — COMMENTED** [review]
Do we distinguish between atomic bloqs and bloqs where the decomposition failed? Because in the former we treat it as a leaf bloq, and in the latter we cannot compute the correct cost. Is my understanding correct?

**Comment by mpharrigan** [comment]
> Do we distinguish between atomic bloqs and bloqs where the decomposition failed? Because in the former we treat it as a leaf bloq, and in the latter we cannot compute the correct cost. Is my understanding correct?

If it's a leaf bloq, `QECGatesCost` should have already determined its cost before trying to peer into its decomposition. If you get to the point in the code where you're trying to look at callees to determine costs: if it's a `DecomposeTypeError` then it's an error since we've reached an atomic, leaf bloq that we don't know how to count; if it's a `DecomposeNotImplementedError` then there are costs that should be from the decomposition but there is no decomposition. So for resource counting, those are both an error condition where we can't return resource counts

**Comment by anurudhp** [comment]
Ah, makes sense, thanks!

**Review by anurudhp — APPROVED** [review]

**Comment by mpharrigan** [comment]
I was going to factor out this change from the fixes i've been making to QECGatesCost but they're somewhat intertwined since this change reveals the failures that need some of the other fixes. Moving to draft

**Comment by mpharrigan** [comment]
subsumed by #1313

**Pull request closed without merging**
