### PR TITLE
Add unary iteration bloq from Cirq-FT

### PR DESCRIPTION
**Pull request by tanujkhattar**
Part of [Qualtran & Cirq-FT Integration](https://docs.google.com/document/d/1miypjcCNt6JV_qAypUVPy5eH3EmKadLqeZomA5QoWK0/edit?usp=sharing&resourcekey=0-ciQ8jPfQmK8gtey2lNKesw)

This is working sooooo nicely. Notice the `assert_valid_bloq_decomposition` in the tests for unary iteration :)

```python
bloq = ApplyXToLthQubit(2, 4, 2)
cbloq = bloq.decompose_bloq()
draw_musical_score(get_musical_score_data(cbloq))
```

image

### CODE REVIEW

**Comment by fdmalone** [comment]
Very nice. bloq_counts and get_bloq_counts_graph work as expected too.

**Comment by fdmalone** [comment]
```
 {Split(n=4): 1,
  Join(n=2): 2,
  TGate(): 16,
  ArbitraryClifford(n=2): 58,
  CirqGateAsBloq(gate=(cirq.Y**0.5)): 7,
  CirqGateAsBloq(gate=(cirq.Y**-0.5)): 7,
  CirqGateAsBloq(gate=cirq.CZ): 7,
  Join(n=4): 1,
  Split(n=2): 2})
```

**Comment by fdmalone** [comment]
Is there anything to review here or is this just copy paste. It could be nice to add some bloq drawings to the notebook in the future.

**Comment by tanujkhattar** [comment]
This is just copy paste for now. Let's add improvements in follow up PRs to keep the complexity manageable. 

I'll start moving other algos once this is merged.

**Comment by fdmalone** [comment]
LGTM

**Review by fdmalone — APPROVED** [review]

**Pull request merged**
