### PR TITLE
Make `Identity` an `n` qubit bloq

### LINKED ISSUE #1207: Add n-bit Identity, implement C[I] = I
We have a one qubit `Identity` bloq. This should probably let you do an n-bit identity operation and the controlled version of it should be an `n+m` bit identity for m control bits.

### PR DESCRIPTION
**Pull request by anurudhp**
fixes #1207 

- `Identity` now accepts a `bitsize`, and has a single register `q` of `QAny(bitsize)`.
- `Identity(n).controlled(m)` is `Identity(n + m)`.

more discussion: https://github.com/quantumlib/Qualtran/pull/1322#issuecomment-2299989824

### CODE REVIEW

**Comment by fdmalone** [comment]
I'm still a little confused about why the Identity being a single qubit bloq is problematic, does OnEach(Identity, n).controlled(m) not do the same thing?

**Comment by tanujkhattar** [comment]
I think `OnEach(Identity(), n).controlled(m)` would probably do the same thing; but I think it's nicer and cleaner to have an n-bit Identity operation that returns itself when controlled.

**Comment by fdmalone** [comment]
Ok, should this still be a basic gate? I think the justification for moving it back to basic gates from #1322 was that it was more logically consistent to be among $I$, $X$, $Y$ and $Z$ and basic gates should probably be restricted to one and two qubit gates maybe? Please ignore me if it makes things easier / better / cleaner.

**Comment by anurudhp** [comment]
Another subtle issue with `OnEach(Identity(), n).controlled(m)` is that it would produce `m` bloqs of `OnEach(Identity(), n + 1)` (because the control qubits are common), and therefore `m * (n + 1)` `Identity()` bloqs. Having a single `Identity(n)` makes it cleaner imo.

**Comment by fdmalone** [comment]
SGTM. Do we need to have both? Probably not right?

**Comment by anurudhp** [comment]
both as in?

**Comment by mpharrigan** [comment]
> I'm still a little confused about why the Identity being a single qubit bloq is problematic, doesOnEach(Identity(), n).controlled(m) not do the same thing?

The motivation is that we _have_ an identity bloq (that is somewhat out of our control; e.g. passed as a class attribute; e.g. in applyLthgate) that we want to control. We could return `OnEach`; but the spirit of qualtran is to give names to things

**Review by mpharrigan — APPROVED** [review]
very nice, thanks so much for this. Lovely use of `add_and_partition`

**Comment by mpharrigan** [comment]
>  SGTM. Do we need to have both? Probably not right?

Not 100% sure what's being asked here, but this PR keeps one `Identity` bloq that has a bitsize that defaults to 1, so there's only one thing to contend with.

**Pull request merged**
