### PR TITLE
Add build_call_graph and symbolic resource estimation to MultiControlPauli

### PR DESCRIPTION
**Pull request by tanujkhattar**
Pulled out from https://github.com/quantumlib/Qualtran/pull/1017

### CODE REVIEW

**Review by fdmalone — APPROVED** [review]
you need to update the notebooks

**Comment by tanujkhattar** [comment]
I don't include the symbolic example in the notebook because we still can't access the signature (and therefore call `show_bloq()` etc.) on the symbolic bloq since the `shape` is symbolic. We still need more work for all these bloqs to either 

(a) Support symbolic `shape` when instantiating a register (less likely)
(b) Refactor the bloqs so that the control register is of type `QAny(symbolic_size)` with `shape=()`. (more likely)

**Comment by fdmalone** [comment]
Ok!

**Comment by mpharrigan** [comment]
Can you open an issue to track the outstanding symbolic ctrl shaped register problem

**Pull request merged**
