### PR TITLE
Replace `_t_complexity_` with `build_call_graph` in comparison gates

### PR DESCRIPTION
**Pull request by tanujkhattar**
Fixes https://github.com/quantumlib/Qualtran/issues/1010

Helps support symbolics and better resource counting for comparison gates. 

Edit: Also updated `LessThanEqual` gate.

### CODE REVIEW

**Comment by NoureldinYosri** [comment]
@tanujkhattar this PR becomes obsolete once I merge my upcoming PR that reimplements all comparison gates + adds missing comparison gates. I will send the PR today.

**Comment by tanujkhattar** [comment]
I think this is a fairly straightforward change, so lets merge this and then I will lookout for your PR with the revamp? In case we are not able to merge your PR in time for the release; this would be a good temporary solution to unblock other upgrades.

**Review by NoureldinYosri — APPROVED** [review]

**Comment by mpharrigan** [comment]
this broke the `leq_symb` bloq example, which tragically isn't included in a unit test

**Comment by tanujkhattar** [comment]
Yeah, I'll send a fix soon. Realized it when implementing symbolic state prep

**Pull request merged**
